### PR TITLE
Added LaunchPads

### PR DESCRIPTION
**Pull request by bvdwalt**
- Added Launchpads under lib/models.
- Added launchpads endpoint.
- Implemented getAllLaunchPads in SpaceXApi.
- Implemented getLaunchPadById in SpaceXApi.
- Implemented queryLaunchPad in SpaceXApi.
- Bumped version to 0.0.4
- Fixed Readme.md to correctly point to examples.

### CODE REVIEW

**Comment by bvdwalt** [comment]
Hi @ahsanz024, please let me know if you would like this included in your package. I had to recently upgrade to v4 of the API and your package has helped make that easier for me, but I realised that there were no methods for getting the Launchpad(s), so I thought I'd add it if possible.

**Comment by ahsanz024** [comment]
@bvdwalt thanks for adding this, i must've missed it.

**Comment by bvdwalt** [comment]
Hi @ahsanz024, no problem at all. Thanks for accepting. I'll make more PRs if there is anything else I notice. 

Would it be possible to update the pub package?

**Comment by ahsanz024** [comment]
@bvdwalt done

**Comment by bvdwalt** [comment]
@ahsanz024 thanks a lot man. Have a great day.

**Pull request merged**
